---
title: "Week 1. Lab Introduction"
date: "Sep. 03 & 04, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Introduction to BIOL 211 Lab

* [Syllabus](https://aroles.github.io/biol211/index.html)


# Lab Safety



# Arthropod Orders 

* Dichotomous key for identifying Insects to Order.


# Finding Sources

* Oberlin libraries [Finding article full-text](https://libraries.oberlin.edu/faqs/faq-22)
* [How to find sources](https://vimeo.com/user5041809/collections)
* Using [Google Scholar](https://scholar.google.com/) to find sources - try the *Cited by* link for relevant sources.

## What is a scholarly source



## Citing Sources



# Assignment

Each person in your group must find a different scholarly source and provide a short summary of the information provided in the source. The citation for your source along with the summary are due before next week's lab. 

You should turn these in using the link in the "Lab Assignment Turn In" drop down menu at the top of the page. Make sure to use the link for your lab section (i.e., if your section meets on Tuesday then you should use the "Tuesday Lab Section" link and if your section meets on Wednesday then you should use the "Wednesday Lab Section" link). 

Your first assignment for lab is to read "[The Importance of Stupidity in Scientific Research](sheets/sci_articles/Importance_of_stupidity.pdf)" which can be downloaded [HERE](sheets/sci_articles/Importance_of_stupidity.pdf).




