---
title: "Week 2. Insect Orders and Developing Hypotheses"
date: "Sep. 10 & 11, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
pkgdown:
  as_is: true
---
# Overview

* [Handouts for Lab 2](sheets/sci_articles/BIOL211_Lab2_Handouts.pdf) (paper copies given in lab)
* [Library Search Guide](https://libguides.oberlin.edu/BIOL211)
* [Claim-Evidence-Reasoning Guide](CER_framework.html)
* Link to RefWorks for creating bibliographies: https://refworks.proquest.com/

# All about arthropods

For this part of lab, we'll learn how to tell apart different Orders and practice with preserved specimens.

### Intro to Insect Orders

* Each team will be assigned 1-2 Orders and is responsible for identifying what characteristics are used to distinguish those Orders from others. 
* You can use the two field guides available in lab to help with this task.
* Each team presents the key features of their Orders to the whole lab. (Take notes on what other teams tell you!)
* Practice using the key in the Peterson's field guide to identify the specimens on the cards from last week to their Order.

### Practice with preserved specimens

* Now that we have key features for each order, examine some already identified preserved specimens. Can you find the key features on these specimens?
* Next, practice with some unknown specimens. Can you identify what Order they belong to? Write up a Claim, with Evidence, and Reasoning (CER format).



# Library visit

Head Science Librarian Eboni Johnson will lead us through an introduction to using library resources to find sources. 

She also created this handy webpage for our class: https://libguides.oberlin.edu/BIOL211

# Assignment (due week 3)

* For next week, you will find and annotate 5 more papers. Together, your group must find 20 total new papers.
  * Use the 3-2-1 format from last time (see instructions below)
  * Collaborate so your group shares a single document to include all 20 sources. 
  * **Submit 1 file for the group.**

## Annotation instructions

* Use a 3-2-1 format for your annotation:
    * Three takeaways from the article that summarize its content.
    * Two ways you think this particular article could apply to our research project.
    * One thing you feel you still don’t understand after reading the article.<br><br>

* Use complete sentences in paragraph format.

* Use Council for Science Editors (CSE) formatting for the actual citation
    * Pay close attention to the style of text (italics, bold, underline, quoted), punctuation separating information, and the order in which info is presented (ex: is the date after the author names or after the date?).
    * General format is: Author(s). Date. Article title. Journal title. Volume(issue):location.
    * Citation generator:  https://www.bibguru.com/c/cse-citation-generator/
    * Citation quick-guide: https://www.scientificstyleandformat.org/Tools/SSF-Citation-Quick-Guide.html
    * Link to RefWorks for creating bibliographies: https://refworks.proquest.com/

# Introduction to our arthropod research project

* Intro to Arboreteum ecosystems and geography
* Intro to available traps, use of traps
* Jigsaw discussion on papers read for today
* In assigned teams, discussion of experimental design and generation of question/hypothesis/predictions
* **Turn in initial draft of question/hypothesis/predictions**







