---
title: "Week 5. Arthropod Sampling 3"
date: "Oct 1 & 2, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
    keep_tex: true
pkgdown:
  as_is: true
---
# Arthropod Sampling Continued

Remember to see the [Week 3 agenda](articles/wk03_sep17.html) for the description of sampling design (number of groups, number of traps of different types)

NOTE: We are modifying the lab calendar as we have decided to expand this arthropod project for the duration of the semester. Keep checking in for details on schedule changes -- basically, we'll take more time than previously planned for this project.

### Week 5 field work (Oct 1-2)
* Collect pitfall traps from last week; set to filter back in lab
* Re-deploy pitfall traps, round 3 
* Deploy combo traps, round 2 [2 groups per lab section, each group deploys 1 trap, cover all four habitats between both lab sections]
* Collect sweep net & beat net samples in each habitat [every group]
* Collect leaf litter samples & set up Berlese funnel traps back in lab 
* Continue ID work on samples from last week




