---
title: "Week 6. Arthropod Sampling 4"
date: "Oct 8 & 9, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
    keep_tex: true
pkgdown:
  as_is: true
---
# Arthropod Sampling Continued

Remember to see the [Week 3 agenda](articles/wk03_sep17.html) for the description of sampling design (number of groups, number of traps of different types)

Below, we outline the current calendar of lab activities.

### Week 6 field work (Sept 24-25)
* Collect pitfall traps from last week; set to filter back in lab
* Collect combo traps from last week; set to filter back in lab
* Collect sweep & beat net samples in each habitat
* Collect leaf litter samples & set up Berlese funnel traps back in lab 
* Continue ID work on samples from last week

You are required to complete open lab hours for this week. See the [Open Lab Hours page](articles/open_lab_hours.html) for times available.

# Assignment due Oct 15/16

* Complete videos 1-4 of the [Intro to R sequence](articles/intro2r.html)
* Complete the Intro2R Assignment 1 (see page from first bullet point)
* Complete 2 hours of open lab hours processing samples and identifying specimens

# Revised 211 Lab Schedule
Revised Oct 8, 2024

| Week | Date | Lab Activity | Assignment Due |
| :--- | :------ | :------------------- | :---------- |
| 1 | Sep 3/4 | Intro (course structure, safety) / background for next time | None |
| 2 | Sep 10/11 | Field method intro / hypothesis generation / library intro | 4-paper annotated bib | 
| 3 | Sep 17/18 | Finalize hypothesis / data collection 1 / begin ID work | Group annotated bib | 
| 4 | Sep 24/25 | Data collection 2 / cont. ID work | None | 
| 5 | Oct 1/2 | Data collection 3 / cont. ID work | Required 2 open lab hours |
| 6 | Oct 8/9 | Data collection 4 / cont. ID work | Required 2 open lab hours |
| 7 | Oct 15/16 | Continue ID work (complete by 10/18) | Required open lab hours, R homework (vid 1-4, assign 1) |
| 8 | Oct 22/23 | Fall Break -- No labs | | 
| 9 | Oct 29/30 | Data entry / begin data cleaning | R homework (vid 5-7, assign 2) |
| 10 | Nov 5/6 | Finish data cleaning / begin data analysis | |
| 11 | Nov 12/13 | Finish data analysis / Presentation prep: begin drafting poster / begin drafting written report | |
|12| Nov 19/20 | Presentation prep: cont. drafting poster & finalize / cont. drafting written report | Poster due 11/26 |
| 13 | Nov 28/29 | Thanksgiving Break - No labs | |
| 14| Dec 3/4 | Finalize written report | Final report due 12/9 | 
| 15 | Dec 10/11 | Poster presentations | Presentation, final reflection | 





