---
title: "Week 7. Arthropod Identification Fest"
date: "Oct 15 & 16, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
    keep_tex: true
pkgdown:
  as_is: true
---
# Arthropod Identification

This week, we are focusing on finishing the IDs for our specimens. Our goal is to have all IDs finished by Friday Oct 18th. If your team finishes yours, you can help with someone else's samples.

Remember you also have one more Burlese funnel sample to filter for ID! Be sure to clean your glassware as you are finisihed with it and put it out to dry.

Below, we outline the current calendar of lab activities.

Note that there is an assigment due the week after break -- finishing the R videos (see below).

# Assignment due Oct 29/30

* Complete videos 5-7 of the [Intro to R sequence](intro2r.html)
* Complete the Intro2R Assignment 2 
* Finish identifying specimens ASAP!

# Data Entry Spreadsheet

We have created a [shared spreadsheet for data entry](https://docs.google.com/spreadsheets/d/1aOY1GEJ3RQp-aX9d0PBbzDfUWzdCdlNjtiTnu9dqfDM/edit?usp=sharing). You will need to fill out the EnterDataHere sheet once for each data sheet that you have (one for each sample). After you submit a sheet, it will appear in the Database. **All data should be entered before 9am on Tue Oct 29.**

Please take care to:

* Only enter data when no one else is using the spreadsheet (only one person can add data at a time).
* Use the EnterDataHere sheet to add your data. Do not add data directly to the Database sheet.
* Capitalize Order and Family names.
* Spell Order and Family names correctly.
* Enter all the identifying information (Group, Dates, trap type, etc) correctly.
* If you have any extra info you can put it in the Notes column.
* Click Submit once all info is entered. You can check the Database sheet to see that your entries were added (scroll to the bottom for the most recent entries).
* Click Clear to remove your data after you have submitted it. Then you can enter a new sheet if desired.
* Please DO NOT modify the Database sheet so that you do not change anyone else's data! I have left it editable (not protected) in case you make a mistake and want to delete your data and re-enter but PLEASE BE CAREFUL not to change anything else.
* Be sure to close the spreadsheet when you are finished.

**If you have any questions or encounter any problems using the spreadsheet please contact Angie.**

# Revised 211 Lab Schedule
Revised Oct 8, 2024

| Week | Date | Lab Activity | Assignment Due |
| :--- | :------ | :------------------- | :---------- |
| 1 | Sep 3/4 | Intro (course structure, safety) / background for next time | None |
| 2 | Sep 10/11 | Field method intro / hypothesis generation / library intro | 4-paper annotated bib | 
| 3 | Sep 17/18 | Finalize hypothesis / data collection 1 / begin ID work | Group annotated bib | 
| 4 | Sep 24/25 | Data collection 2 / cont. ID work | None | 
| 5 | Oct 1/2 | Data collection 3 / cont. ID work | Required 2 open lab hours |
| 6 | Oct 8/9 | Data collection 4 / cont. ID work | Required 2 open lab hours |
| 7 | Oct 15/16 | Continue ID work (complete by 10/18) | Required open lab hours, R homework (vid 1-4, assign 1) |
| 8 | Oct 22/23 | Fall Break -- No labs | | 
| 9 | Oct 29/30 | Data entry / begin data cleaning | R homework (vid 5-7, assign 2) |
| 10 | Nov 5/6 | Finish data cleaning / begin data analysis | TBD |
| 11 | Nov 12/13 | Finish data analysis / Presentation prep: begin drafting poster / begin drafting written report | TBD |
|12| Nov 19/20 | Presentation prep: cont. drafting poster & finalize / cont. drafting written report | Poster due 11/26 |
| 13 | Nov 28/29 | Thanksgiving Break - No labs | TBD |
| 14| Dec 3/4 | Finalize written report | Final report due 12/9 | 
| 15 | Dec 10/11 | Poster presentations | Presentation, final reflection | 





