---
title: "Week 9. Arthropod Biodiversity: Begin data cleanup"
date: "Oct 29 & 30, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
    keep_tex: true
pkgdown:
  as_is: true
---
# Arthropod Identification - complete!

Any outstanding samples that should be included in our dataset need to be identified and added to the spreadsheet by the end of lab this week.

Once you have completed IDs for a sample, add that data to the shared database: https://docs.google.com/spreadsheets/d/1aOY1GEJ3RQp-aX9d0PBbzDfUWzdCdlNjtiTnu9dqfDM/edit?usp=sharing

Be careful to follow directions and do not directly edit the database itself (unless you need to fix data entered incorrectly).

**If you have any questions or encounter any problems using the spreadsheet please contact Angie.**


# Revisit experimental design principles

* Begin working in teams on experimental design handout.
* Identify types of graphs that you might create to address question, test hypothesis.
* Identify whether you will need to create new variables or calculate variables using the existing raw dataset.
* Think about the existing variables and what their roles are in our experimental design (see handout).

# Review how to clean our dataset 

Note that you cannot begin to clean the full dataset until all data has been entered. We will go over what to do and pay attention to together but you will do the cleaning later on your own.

Every student must clean the dataset -- practice is how we learn this skill!

Begin by opening the [dataset spreadsheet](https://docs.google.com/spreadsheets/d/1aOY1GEJ3RQp-aX9d0PBbzDfUWzdCdlNjtiTnu9dqfDM/edit?usp=sharing) and making a copy for yourself, saved to your google drive. Go to File -> Make a Copy. 

Scroll through the database and identify problems that will need to be cleaned up. When you find a cleanup issue, report it on the Cleanup Issues sheet.

Next week, you will turn in the cleaned version of this completed dataset (once all data has been added). 

# Activities to work on in lab today

* Data entry: finish and double-check work against database. Add check mark and signature at bottom of sheets with verified entries.
* Dataset clean-up: begin looking through the dataset to identify problems and find solutions for them; will need to wait to actually make changes until all data is entered.
* **Complete the experimental design framework sheet -- due at end of lab period**
* Cleanup materials: return ID kits to back left counter space. Place data sheets and field notebooks in designated spaces.
* Finish the R Intro exercises if necessary.



# Revised 211 Lab Schedule
Revised Oct 8, 2024

| Week | Date | Lab Activity | Assignment Due |
| :--- | :------ | :------------------- | :---------- |
| 1 | Sep 3/4 | Intro (course structure, safety) / background for next time | None |
| 2 | Sep 10/11 | Field method intro / hypothesis generation / library intro | 4-paper annotated bib | 
| 3 | Sep 17/18 | Finalize hypothesis / data collection 1 / begin ID work | Group annotated bib | 
| 4 | Sep 24/25 | Data collection 2 / cont. ID work | None | 
| 5 | Oct 1/2 | Data collection 3 / cont. ID work | Required 2 open lab hours |
| 6 | Oct 8/9 | Data collection 4 / cont. ID work | Required 2 open lab hours |
| 7 | Oct 15/16 | Continue ID work (complete by 10/18) | Required open lab hours, R homework (vid 1-4, assign 1) |
| 8 | Oct 22/23 | Fall Break -- No labs | | 
| 9 | Oct 29/30 | Data entry / begin data cleaning | R homework (vid 5-7, assign 2) |
| 10 | Nov 5/6 | Finish data cleaning / begin data analysis | Cleaned dataset |
| 11 | Nov 12/13 | Finish data analysis / Presentation prep: begin drafting poster / begin drafting written report | TBD |
|12| Nov 19/20 | Presentation prep: cont. drafting poster & finalize / cont. drafting written report | Poster due 11/26 |
| 13 | Nov 28/29 | Thanksgiving Break - No labs | TBD |
| 14| Dec 3/4 | Finalize written report | Final report due 12/9 | 
| 15 | Dec 10/11 | Poster presentations | Presentation, final reflection | 





