---
title: "Week 10. Arthropod Biodiversity: Data Analysis & Posters"
date: "Nov 5 & 6, 2024"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
  pdf_document:
    toc: TRUE
    toc_depth: 3
    keep_tex: true
pkgdown:
  as_is: true
---
This week in lab we are focused on finishing cleaning our dataset and starting to make plots and analyze our data. We'll also start thinking about the poster presentation each group will be making, mostly starting next week.

# Arthropod Database Stats and Cleanup

We had a total of 1513 samples counted and identified to at least Order. Our dataset comprises 618 total rows of data. There were 47 specimens id'd to Order but not Family. There were 32 Orders and 156 Families represented, after correcting about 145 errors in Order and Family names. 

For additional details or to check your cleaned dataset against, you can download Angie's cleaned dataset [here](https://drive.google.com/file/d/19dZeDDTy5KHCDA6_jcajipbjfEpGzVYF/view?usp=drive_link) (after 5p on Wed Nov 6).

Phew! That was a lot of work and a good size dataset that we assembled.

You will need to discuss with your team which samples you may need to discard before you graph and analyze your data. For example, everyone will want to get rid of the samples that have no order or family ID. But if you are not comparing different types of traps, you may want to keep the sample that came from beat and sweep net samples that were combined into one.

# Next Data Steps -- Graphing and Analysis  

Revisit your group's hypothesis and predictions. What comparisons are you interested in making with this dataset that will help to address your hypothesis?

Do you need to create any new variables? These could be grouping variables (like making a new site variable for just 4 values: riparian, open.field, forest.interior, forest.edge). Plus you probably need to make some response variables, like S, H, and E that we used before. Can you think of any other variables that you might need as explanatory variables or that you could use as response variables? What about sampleid, would that be useful? (It can mostly be useful in tracking down particular samples.)

Always remember to check that the code that you run did what you wanted it to do by viewing the dataset or printing a result to the console.

Work with your team on figuring out your analysis and try to get it done in R. Talk to your TA and/or instructor after you have given it a go if you need assistance OR just want them to review your plan.

# Getting Ready For Posters!

As we mentioned previously, the two final products we'll have from this semester are (1) a poster presentation, one per group (occurs Dec 10/111) and (2) a final report collaboratively written by the entire lab section. 
Today we're sharing with you a [template for the poster](https://docs.google.com/presentation/d/1YDqIf1smF_hxcFGkc0tGqOuUXkX5RqCW/edit?usp=drive_link&ouid=107508568211857334485&rtpof=true&sd=true). You can download a copy for yourself and make changes to suit your presentation. Keep in mind that font sizes on the template were chosen to be readable at an appropriate distance so consider not changing those!

Be sure to walk around the department and observe the posters on the wall. Which ones do you think are well done? Why? Use those examples to help you make good design decisions for your poster.

If you took photos of the field sites, those would be great to include with your poster. You might also be interested in the maps of the field site that we shared when we first went into the field. Here are those two maps:

* [Map with zones clearly delineated](https://drive.google.com/file/d/1szE_Q9TAmCqW_o_CduEGerk2jYzmHxXc/view?usp=drive_link)
* [Map with zones roughly delineated - satellite image](https://drive.google.com/file/d/1ojLTeRK-fSJgiMQUZ-Tk_nIhZULAcSXv/view?usp=drive_link)

Remember that the papers you read at the start of the semester will be good resources for background for the poster (and later the report). 

Keep in mind that you want to use fonts that are easy for the observer to read. You can search for guidance about font sizes... here's [one good resource](https://urc.ucdavis.edu/sites/g/files/dgvnsk3561/files/inline-files/General%20Poster%20Design%20Principles%20-%20Handout.pdf).

# Revised 211 Lab Schedule
Revised Oct 8, 2024

| Week | Date | Lab Activity | Assignment Due |
| :--- | :------ | :------------------- | :---------- |
| 1 | Sep 3/4 | Intro (course structure, safety) / background for next time | None |
| 2 | Sep 10/11 | Field method intro / hypothesis generation / library intro | 4-paper annotated bib | 
| 3 | Sep 17/18 | Finalize hypothesis / data collection 1 / begin ID work | Group annotated bib | 
| 4 | Sep 24/25 | Data collection 2 / cont. ID work | None | 
| 5 | Oct 1/2 | Data collection 3 / cont. ID work | Required 2 open lab hours |
| 6 | Oct 8/9 | Data collection 4 / cont. ID work | Required 2 open lab hours |
| 7 | Oct 15/16 | Continue ID work (complete by 10/18) | Required open lab hours, R homework (vid 1-4, assign 1) |
| 8 | Oct 22/23 | Fall Break -- No labs | | 
| 9 | Oct 29/30 | Data entry / begin data cleaning | R homework (vid 5-7, assign 2) |
| 10 | Nov 5/6 | Finish data cleaning / begin data analysis | Cleaned dataset |
| 11 | Nov 12/13 | Finish data analysis / Presentation prep: begin drafting poster / begin drafting written report | TBD |
|12| Nov 19/20 | Presentation prep: cont. drafting poster & finalize / cont. drafting written report | Poster due 11/26 |
| 13 | Nov 28/29 | Thanksgiving Break - No labs | -- |
| 14| Dec 3/4 | Finalize written report | Final report due 12/9 | 
| 15 | Dec 10/11 | Poster presentations | Presentation, final reflection | 





